version: "3.2"
services:
  frontend:
    image: inpost-frontend
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile.frontend

  backend:
    image: inpost-backend
    ports:
      - "7169:80"
    build:
      context: .
      dockerfile: Dockerfile.backend

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MOCNEHASLO1234!@###"
      ACCEPT_EULA: "Y"